# Generated by Django 4.2.11 on 2024-03-15 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6df1d786-c8c2-44b4-84d5-e9656a506496'), editable=False, primary_key=True, serialize=False),
        ),
    ]
